version: '3.8'

services:
  hgvs:
    image: hgvs
    build: .
    ports:
      - "8002:8002"
    environment:
      - FASTA=tests/fixtures/Homo_sapiens.GRCh38.dna.chromosome.X.Y.fa
      - REFGENE=tests/fixtures/genes.refGene
